### ISSUE TITLE
Add ability to specify tag in config

### ISSUE THREAD

**Issue by igrybkov** [mrsimpson/action-openfaas-build#16]
Hi, would be nice to be able to specify a tag during the build in the config so the image would be published with, for example, a branch-named tag or with `latest` tag without the suffix.

**Comment by mrsimpson** [comment]
Sounds reasonable. I have not had a look at the tool for a long time, but I might give it a shot.

**Comment by mrsimpson** [comment]
@igrybkov As per your requirement to tag `latest`: particularly in the context of OpenFaaS functions and CICD I consider this not a good practice: when doing this, you cannot easily know which version of the function is being executed / has been executed. Also, the ImagePullPolicy May lead to the new version not being deployed at all if improperly configured. 
I just recalled that when I implemented this, I knowingly selected the readable but unique image tag generation. 
Therefore, I don't prioritize this issue for now.

**Comment by igrybkov** [comment]
I already started working on it just because I need it, so I could send you a PR in a next couple of days as long as it makes sense for you too.
I agree that in production you should know with which version you're working, but even in this case I'll likely prefer tags or something more meaningful than a hash. It's also a big deal on a development environment where you don't want to change image name every deployment.
What I'm going to do in my changes is to add a possibility to set an alias so you could keep existing naming convention and also set a second tag for the same image.

**Comment by mrsimpson** [comment]
@igrybkov Great, all PRs are welcome! 
As far as I recall, there is even something like a CD for the action itself. It may fail when deploying it, since I might have torn down the cluster, so don't get irritated by that
